//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShop.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Dialog
    {
        public int DialogID { get; set; }
        public int DialogPID { get; set; }
        public int ConsultUID { get; set; }
        public string ConsultContent { get; set; }
        public System.DateTime ConsultTime { get; set; }
        public int ReplyUID { get; set; }
        public string ReplyContent { get; set; }
        public Nullable<System.DateTime> ReplyTime { get; set; }
        public int DialogOver { get; set; }
        public int DelFlag { get; set; }
    }
}
