//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShop.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_UserOrder
    {
        public int OrderID { get; set; }
        public int PID { get; set; }
        public int UID { get; set; }
        public int PUID { get; set; }
        public Nullable<int> ISPay { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public Nullable<int> DelFlag { get; set; }
    }
}
