//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShop.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_Users
    {
        public int UID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public System.DateTime RegistTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public string Address { get; set; }
        public Nullable<int> Gender { get; set; }
        public string HeadImage { get; set; }
        public string IDNumber { get; set; }
        public string QQNumber { get; set; }
        public string note { get; set; }
        public Nullable<int> CreditValue { get; set; }
        public Nullable<int> DelFlag { get; set; }
    }
}
