//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShop.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_UserAttention
    {
        public int UserAttentionID { get; set; }
        public Nullable<int> AttrntionUID { get; set; }
        public Nullable<int> AttentionPID { get; set; }
        public Nullable<int> ProductUID { get; set; }
        public Nullable<System.DateTime> AttentionTime { get; set; }
        public Nullable<int> DelFalg { get; set; }
    }
}
