//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolShop.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_MyAttentions
    {
        public Nullable<int> AttentionPID { get; set; }
        public Nullable<int> ProductUID { get; set; }
        public Nullable<System.DateTime> AttentionTime { get; set; }
        public int UserAttentionID { get; set; }
        public string ProductName { get; set; }
        public decimal ProductPrice { get; set; }
        public string ImgURL { get; set; }
        public string PhoneNumber { get; set; }
        public string Describe { get; set; }
        public Nullable<int> AttrntionUID { get; set; }
        public string NickName { get; set; }
        public string RealName { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> DelFalg { get; set; }
    }
}
